# Generated by Django 4.2 on 2023-05-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
