# Generated by Django 4.2 on 2023-05-06 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0002_scheduler_address_alter_doctor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, choices=[('08 AM to 09 AM', '08 AM to 09 AM'), ('09 AM to 10 AM', '09 AM to 10 AM'), ('10 AM to 11 AM', '10 AM to 11 AM'), ('11 AM to 12 PM', '11 AM to 12 PM'), ('12 PM to 01 PM', '12 PM to 01 PM'), ('01 PM to 02 PM', '01 PM to 02 PM'), ('03 PM to 03 PM', '02 PM to 03 PM'), ('04 PM to 05 PM', '04 PM to 05 PM')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentist_app.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='issue',
            field=models.CharField(blank=True, choices=[('Whitening', 'Whitening'), ('Toothache', 'Toothache')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
