# Generated by Django 4.2 on 2023-05-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0004_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostics', models.TextField(max_length=300)),
                ('treatment', models.TextField(max_length=300)),
                ('bp', models.TextField(max_length=300)),
                ('weight', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('doctor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentist_app.doctor')),
                ('patient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentist_app.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Sessions',
        ),
    ]
