# Generated by Django 4.2 on 2023-05-10 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0005_consultation_delete_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='weight',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnostics',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='treatment',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('others', models.TextField(max_length=500)),
                ('patient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentist_app.patient')),
            ],
        ),
    ]
