# Generated by Django 4.2 on 2023-05-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0006_remove_consultation_bp_remove_consultation_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='allergies',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='family',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='bp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='height',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='others',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='weight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
